// AUTO-GENERATED by buildCities.cjs. DO NOT EDIT.
import type { CityLayer } from '../../types';
export const citiesLayer: CityLayer = {
  "key": "cities",
  "label": "Cities (2025)",
  "features": [
    {
      "id": "0100100",
      "name": "Abanda CDP",
      "x": 658.87,
      "y": 401.86,
      "lon": -85.527,
      "lat": 33.0916,
      "population": null
    },
    {
      "id": "0100124",
      "name": "Abbeville city",
      "x": 666.25,
      "y": 429.91,
      "lon": -85.2592,
      "lat": 31.5652,
      "population": null
    },
    {
      "id": "0100460",
      "name": "Adamsville city",
      "x": 635.59,
      "y": 394.59,
      "lon": -86.9715,
      "lat": 33.6023,
      "population": null
    },
    {
      "id": "0100484",
      "name": "Addison town",
      "x": 631.36,
      "y": 383.63,
      "lon": -87.178,
      "lat": 34.2027,
      "population": null
    },
    {
      "id": "0100676",
      "name": "Akron town",
      "x": 624.92,
      "y": 409.23,
      "lon": -87.7409,
      "lat": 32.8791,
      "population": null
    },
    {
      "id": "0100820",
      "name": "Alabaster city",
      "x": 638.58,
      "y": 401.64,
      "lon": -86.8231,
      "lat": 33.2144,
      "population": null
    },
    {
      "id": "0100988",
      "name": "Albertville city",
      "x": 646.02,
      "y": 381.04,
      "lon": -86.2107,
      "lat": 34.2631,
      "population": null
    },
    {
      "id": "0101132",
      "name": "Alexander City city",
      "x": 652.82,
      "y": 405.82,
      "lon": -85.9406,
      "lat": 32.9167,
      "population": null
    },
    {
      "id": "0101180",
      "name": "Alexandria CDP",
      "x": 652.19,
      "y": 389.91,
      "lon": -85.872,
      "lat": 33.7608,
      "population": null
    },
    {
      "id": "0101228",
      "name": "Aliceville city",
      "x": 618.04,
      "y": 405.2,
      "lon": -88.1593,
      "lat": 33.1237,
      "population": null
    },
    {
      "id": "0101396",
      "name": "Allgood town",
      "x": 642.03,
      "y": 388.18,
      "lon": -86.5161,
      "lat": 33.9076,
      "population": null
    },
    {
      "id": "0101660",
      "name": "Altoona town",
      "x": 645.01,
      "y": 385.37,
      "lon": -86.3052,
      "lat": 34.04,
      "population": null
    },
    {
      "id": "0101708",
      "name": "Andalusia city",
      "x": 647.5,
      "y": 436.74,
      "lon": -86.478,
      "lat": 31.3094,
      "population": null
    },
    {
      "id": "0101756",
      "name": "Anderson town",
      "x": 628.66,
      "y": 370.38,
      "lon": -87.2743,
      "lat": 34.9157,
      "population": null
    },
    {
      "id": "0101852",
      "name": "Anniston city",
      "x": 653.3,
      "y": 391.44,
      "lon": -85.8109,
      "lat": 33.6735,
      "population": null
    },
    {
      "id": "0102116",
      "name": "Arab city",
      "x": 641.46,
      "y": 380.19,
      "lon": -86.5012,
      "lat": 34.3324,
      "population": null
    },
    {
      "id": "0102260",
      "name": "Ardmore town",
      "x": 635.27,
      "y": 368.39,
      "lon": -86.829,
      "lat": 34.9878,
      "population": null
    },
    {
      "id": "0102320",
      "name": "Argo city",
      "x": 642.58,
      "y": 392.1,
      "lon": -86.5058,
      "lat": 33.6979,
      "population": null
    },
    {
      "id": "0102428",
      "name": "Ariton town",
      "x": 659.02,
      "y": 430.09,
      "lon": -85.7131,
      "lat": 31.5978,
      "population": null
    },
    {
      "id": "0102500",
      "name": "Arley town",
      "x": 630.97,
      "y": 386.06,
      "lon": -87.2178,
      "lat": 34.0762,
      "population": null
    },
    {
      "id": "0102836",
      "name": "Ashford city",
      "x": 667.42,
      "y": 436.95,
      "lon": -85.2362,
      "lat": 31.1853,
      "population": null
    },
    {
      "id": "0102860",
      "name": "Ashland town",
      "x": 653.77,
      "y": 399.04,
      "lon": -85.8337,
      "lat": 33.2699,
      "population": null
    },
    {
      "id": "0102908",
      "name": "Ashville city",
      "x": 645.94,
      "y": 389.16,
      "lon": -86.27,
      "lat": 33.8352,
      "population": null
    },
    {
      "id": "0102956",
      "name": "Athens city",
      "x": 633.8,
      "y": 372.48,
      "lon": -86.9508,
      "lat": 34.779,
      "population": null
    },
    {
      "id": "0103004",
      "name": "Atmore city",
      "x": 632.28,
      "y": 441.68,
      "lon": -87.4578,
      "lat": 31.1241,
      "population": null
    },
    {
      "id": "0103028",
      "name": "Attalla city",
      "x": 647.93,
      "y": 386.09,
      "lon": -86.121,
      "lat": 33.9862,
      "population": null
    },
    {
      "id": "0103076",
      "name": "Auburn city",
      "x": 660.43,
      "y": 410.86,
      "lon": -85.491,
      "lat": 32.6071,
      "population": null
    },
    {
      "id": "0103220",
      "name": "Autaugaville town",
      "x": 642.57,
      "y": 416.03,
      "lon": -86.6588,
      "lat": 32.4326,
      "population": null
    },
    {
      "id": "0103364",
      "name": "Avon town",
      "x": 666.75,
      "y": 437.13,
      "lon": -85.2792,
      "lat": 31.1797,
      "population": null
    },
    {
      "id": "0103508",
      "name": "Axis CDP",
      "x": 623.62,
      "y": 446.24,
      "lon": -88.0226,
      "lat": 30.9222,
      "population": null
    },
    {
      "id": "0103556",
      "name": "Babbie town",
      "x": 650.02,
      "y": 436.62,
      "lon": -86.3194,
      "lat": 31.3021,
      "population": null
    },
    {
      "id": "0103676",
      "name": "Baileyton town",
      "x": 639.95,
      "y": 381.7,
      "lon": -86.6088,
      "lat": 34.2609,
      "population": null
    },
    {
      "id": "0103724",
      "name": "Bakerhill town",
      "x": 665.23,
      "y": 426.02,
      "lon": -85.2954,
      "lat": 31.7769,
      "population": null
    },
    {
      "id": "0103820",
      "name": "Ballplay CDP",
      "x": 652.74,
      "y": 384.88,
      "lon": -85.8015,
      "lat": 34.023,
      "population": null
    },
    {
      "id": "0103940",
      "name": "Banks town",
      "x": 656.65,
      "y": 426.28,
      "lon": -85.8364,
      "lat": 31.8133,
      "population": null
    },
    {
      "id": "0104660",
      "name": "Bay Minette city",
      "x": 627.34,
      "y": 446.52,
      "lon": -87.7928,
      "lat": 30.8903,
      "population": null
    },
    {
      "id": "0104684",
      "name": "Bayou La Batre city",
      "x": 620.57,
      "y": 456.17,
      "lon": -88.2633,
      "lat": 30.4076,
      "population": null
    },
    {
      "id": "0104852",
      "name": "Bear Creek town",
      "x": 623.09,
      "y": 383.37,
      "lon": -87.7134,
      "lat": 34.2555,
      "population": null
    },
    {
      "id": "0104900",
      "name": "Beatrice town",
      "x": 635.18,
      "y": 429.94,
      "lon": -87.209,
      "lat": 31.7333,
      "population": null
    },
    {
      "id": "0104948",
      "name": "Beaverton town",
      "x": 618.89,
      "y": 389.79,
      "lon": -88.0218,
      "lat": 33.9354,
      "population": null
    },
    {
      "id": "0105140",
      "name": "Belgreen CDP",
      "x": 620.47,
      "y": 379.46,
      "lon": -87.8617,
      "lat": 34.4745,
      "population": null
    },
    {
      "id": "0105164",
      "name": "Belk town",
      "x": 620.77,
      "y": 394.99,
      "lon": -87.9286,
      "lat": 33.6516,
      "population": null
    },
    {
      "id": "0105188",
      "name": "Bellamy CDP",
      "x": 619.49,
      "y": 417.54,
      "lon": -88.1315,
      "lat": 32.4637,
      "population": null
    },
    {
      "id": "0105212",
      "name": "Belle Fontaine CDP",
      "x": 622.97,
      "y": 454.44,
      "lon": -88.1059,
      "lat": 30.4895,
      "population": null
    },
    {
      "id": "0105692",
      "name": "Benton town",
      "x": 640.31,
      "y": 418.6,
      "lon": -86.8175,
      "lat": 32.3079,
      "population": null
    },
    {
      "id": "0105812",
      "name": "Berlin town",
      "x": 637.95,
      "y": 383.33,
      "lon": -86.749,
      "lat": 34.185,
      "population": null
    },
    {
      "id": "0105932",
      "name": "Berry town",
      "x": 625.66,
      "y": 394.28,
      "lon": -87.6093,
      "lat": 33.6667,
      "population": null
    },
    {
      "id": "0105980",
      "name": "Bessemer city",
      "x": 636,
      "y": 398.93,
      "lon": -86.9715,
      "lat": 33.3709,
      "population": null
    },
    {
      "id": "0106460",
      "name": "Billingsley town",
      "x": 641.39,
      "y": 411.76,
      "lon": -86.7067,
      "lat": 32.6647,
      "population": null
    },
    {
      "id": "0107000",
      "name": "Birmingham city",
      "x": 638.41,
      "y": 395.74,
      "lon": -86.797,
      "lat": 33.5272,
      "population": null
    },
    {
      "id": "0107120",
      "name": "Black town",
      "x": 659.72,
      "y": 441.12,
      "lon": -85.7444,
      "lat": 31.0098,
      "population": null
    },
    {
      "id": "0107456",
      "name": "Blountsville town",
      "x": 640.67,
      "y": 385.13,
      "lon": -86.5839,
      "lat": 34.0758,
      "population": null
    },
    {
      "id": "0107588",
      "name": "Blue Ridge CDP",
      "x": 649.88,
      "y": 414.04,
      "lon": -86.1824,
      "lat": 32.4989,
      "population": null
    },
    {
      "id": "0107672",
      "name": "Blue Springs town",
      "x": 662.19,
      "y": 428.5,
      "lon": -85.5035,
      "lat": 31.6635,
      "population": null
    },
    {
      "id": "0107912",
      "name": "Boaz city",
      "x": 646.99,
      "y": 382.16,
      "lon": -86.1552,
      "lat": 34.199,
      "population": null
    },
    {
      "id": "0108104",
      "name": "Boligee town",
      "x": 620.62,
      "y": 411.7,
      "lon": -88.0286,
      "lat": 32.7681,
      "population": null
    },
    {
      "id": "0108248",
      "name": "Bon Air town",
      "x": 646.16,
      "y": 400.03,
      "lon": -86.3272,
      "lat": 33.2594,
      "population": null
    },
    {
      "id": "0108272",
      "name": "Bon Secour CDP",
      "x": 629.36,
      "y": 457.11,
      "lon": -87.7244,
      "lat": 30.3182,
      "population": null
    },
    {
      "id": "0108680",
      "name": "Boykin CDP",
      "x": 633.26,
      "y": 423.79,
      "lon": -87.2943,
      "lat": 32.0684,
      "population": null
    },
    {
      "id": "0109016",
      "name": "Brantley town",
      "x": 650.48,
      "y": 431.29,
      "lon": -86.2568,
      "lat": 31.582,
      "population": null
    },
    {
      "id": "0109064",
      "name": "Brantleyville CDP",
      "x": 637.65,
      "y": 401.64,
      "lon": -86.8825,
      "lat": 33.2193,
      "population": null
    },
    {
      "id": "0109136",
      "name": "Brent city",
      "x": 633.65,
      "y": 407.2,
      "lon": -87.1721,
      "lat": 32.9449,
      "population": null
    },
    {
      "id": "0109208",
      "name": "Brewton city",
      "x": 638.37,
      "y": 441.4,
      "lon": -87.0766,
      "lat": 31.1092,
      "population": null
    },
    {
      "id": "0109328",
      "name": "Bridgeport city",
      "x": 652.05,
      "y": 367.39,
      "lon": -85.7238,
      "lat": 34.9493,
      "population": null
    },
    {
      "id": "0109400",
      "name": "Brighton city",
      "x": 636.28,
      "y": 397.6,
      "lon": -86.9454,
      "lat": 33.4396,
      "population": null
    },
    {
      "id": "0109424",
      "name": "Brilliant town",
      "x": 622.62,
      "y": 387.76,
      "lon": -87.769,
      "lat": 34.0257,
      "population": null
    },
    {
      "id": "0109457",
      "name": "Bristow Cove CDP",
      "x": 645.85,
      "y": 383.98,
      "lon": -86.241,
      "lat": 34.1092,
      "population": null
    },
    {
      "id": "0109500",
      "name": "Brook Highland CDP",
      "x": 640.3,
      "y": 397.24,
      "lon": -86.6853,
      "lat": 33.438,
      "population": null
    },
    {
      "id": "0109736",
      "name": "Brookside town",
      "x": 636.74,
      "y": 393.81,
      "lon": -86.8927,
      "lat": 33.6374,
      "population": null
    },
    {
      "id": "0109808",
      "name": "Brookwood city",
      "x": 630.67,
      "y": 401.9,
      "lon": -87.3315,
      "lat": 33.2398,
      "population": null
    },
    {
      "id": "0109880",
      "name": "Broomtown CDP",
      "x": 656.15,
      "y": 378.01,
      "lon": -85.5321,
      "lat": 34.3657,
      "population": null
    },
    {
      "id": "0110240",
      "name": "Brundidge city",
      "x": 657.14,
      "y": 428.03,
      "lon": -85.8175,
      "lat": 31.7176,
      "population": null
    },
    {
      "id": "0110456",
      "name": "Bucks CDP",
      "x": 623.41,
      "y": 444.48,
      "lon": -88.0264,
      "lat": 31.0169,
      "population": null
    },
    {
      "id": "0111032",
      "name": "Butler town",
      "x": 618.82,
      "y": 424.52,
      "lon": -88.2108,
      "lat": 32.0965,
      "population": null
    },
    {
      "id": "0111416",
      "name": "Calera city",
      "x": 639.95,
      "y": 403.25,
      "lon": -86.7456,
      "lat": 33.1223,
      "population": null
    },
    {
      "id": "0111488",
      "name": "Calvert CDP",
      "x": 623.28,
      "y": 441.98,
      "lon": -88.0215,
      "lat": 31.1499,
      "population": null
    },
    {
      "id": "0111512",
      "name": "Camden city",
      "x": 633.46,
      "y": 425.09,
      "lon": -87.2889,
      "lat": 31.9985,
      "population": null
    },
    {
      "id": "0111680",
      "name": "Camp Hill town",
      "x": 657.48,
      "y": 407.58,
      "lon": -85.6558,
      "lat": 32.7973,
      "population": null
    },
    {
      "id": "0112016",
      "name": "Carbon Hill city",
      "x": 626.62,
      "y": 389.88,
      "lon": -87.5221,
      "lat": 33.895,
      "population": null
    },
    {
      "id": "0112040",
      "name": "Cardiff town",
      "x": 636.14,
      "y": 393.69,
      "lon": -86.9306,
      "lat": 33.6473,
      "population": null
    },
    {
      "id": "0112070",
      "name": "Carlisle-Rockledge CDP",
      "x": 647.63,
      "y": 383.69,
      "lon": -86.1241,
      "lat": 34.1145,
      "population": null
    },
    {
      "id": "0112112",
      "name": "Carlton CDP",
      "x": 625.92,
      "y": 438.02,
      "lon": -87.8357,
      "lat": 31.3486,
      "population": null
    },
    {
      "id": "0112160",
      "name": "Carolina town",
      "x": 646.96,
      "y": 438.21,
      "lon": -86.521,
      "lat": 31.2341,
      "population": null
    },
    {
      "id": "0112304",
      "name": "Carrollton town",
      "x": 618.82,
      "y": 402.52,
      "lon": -88.0951,
      "lat": 33.2619,
      "population": null
    },
    {
      "id": "0112496",
      "name": "Castleberry town",
      "x": 638.78,
      "y": 437.77,
      "lon": -87.0291,
      "lat": 31.2997,
      "population": null
    },
    {
      "id": "0112544",
      "name": "Catherine CDP",
      "x": 630.3,
      "y": 421.84,
      "lon": -87.47,
      "lat": 32.1862,
      "population": null
    },
    {
      "id": "0112760",
      "name": "Cedar Bluff town",
      "x": 655.59,
      "y": 380.81,
      "lon": -85.5886,
      "lat": 34.2214,
      "population": null
    },
    {
      "id": "0113264",
      "name": "Center Point city",
      "x": 639.93,
      "y": 393.38,
      "lon": -86.6846,
      "lat": 33.6439,
      "population": null
    },
    {
      "id": "0113648",
      "name": "Centre city",
      "x": 654.46,
      "y": 382.23,
      "lon": -85.6717,
      "lat": 34.1531,
      "population": null
    },
    {
      "id": "0113672",
      "name": "Centreville city",
      "x": 634.25,
      "y": 406.88,
      "lon": -87.132,
      "lat": 32.959,
      "population": null
    },
    {
      "id": "0114008",
      "name": "Chatom town",
      "x": 619.23,
      "y": 436.31,
      "lon": -88.246,
      "lat": 31.4691,
      "population": null
    },
    {
      "id": "0114104",
      "name": "Chelsea city",
      "x": 641.31,
      "y": 399.58,
      "lon": -86.6351,
      "lat": 33.309,
      "population": null
    },
    {
      "id": "0114152",
      "name": "Cherokee town",
      "x": 618.44,
      "y": 374.27,
      "lon": -87.9656,
      "lat": 34.7577,
      "population": null
    },
    {
      "id": "0114202",
      "name": "Cherokee Ridge town",
      "x": 640.34,
      "y": 378.63,
      "lon": -86.5633,
      "lat": 34.4209,
      "population": null
    },
    {
      "id": "0114392",
      "name": "Chickasaw city",
      "x": 622.95,
      "y": 449.13,
      "lon": -88.0797,
      "lat": 30.7715,
      "population": null
    },
    {
      "id": "0114464",
      "name": "Childersburg city",
      "x": 645.89,
      "y": 399.43,
      "lon": -86.3409,
      "lat": 33.2926,
      "population": null
    },
    {
      "id": "0114728",
      "name": "Choccolocco CDP",
      "x": 654.91,
      "y": 391.38,
      "lon": -85.7072,
      "lat": 33.6677,
      "population": null
    },
    {
      "id": "0114968",
      "name": "Chunchula CDP",
      "x": 620.66,
      "y": 446.39,
      "lon": -88.2082,
      "lat": 30.9272,
      "population": null
    },
    {
      "id": "0115064",
      "name": "Citronelle city",
      "x": 619.73,
      "y": 443.27,
      "lon": -88.2498,
      "lat": 31.0973,
      "population": null
    },
    {
      "id": "0115136",
      "name": "Clanton city",
      "x": 642.41,
      "y": 408.24,
      "lon": -86.6195,
      "lat": 32.8456,
      "population": null
    },
    {
      "id": "0115256",
      "name": "Clay city",
      "x": 641.01,
      "y": 392.28,
      "lon": -86.6082,
      "lat": 33.6966,
      "population": null
    },
    {
      "id": "0115304",
      "name": "Clayhatchee town",
      "x": 659.62,
      "y": 436.84,
      "lon": -85.7215,
      "lat": 31.2369,
      "population": null
    },
    {
      "id": "0115376",
      "name": "Clayton city",
      "x": 662.42,
      "y": 424.34,
      "lon": -85.4605,
      "lat": 31.8823,
      "population": null
    },
    {
      "id": "0115472",
      "name": "Cleveland town",
      "x": 641.16,
      "y": 386.48,
      "lon": -86.5614,
      "lat": 34.0022,
      "population": null
    },
    {
      "id": "0115640",
      "name": "Clio city",
      "x": 660.41,
      "y": 427.85,
      "lon": -85.611,
      "lat": 31.7085,
      "population": null
    },
    {
      "id": "0116000",
      "name": "Coaling city",
      "x": 630.5,
      "y": 403.24,
      "lon": -87.3499,
      "lat": 33.1699,
      "population": null
    },
    {
      "id": "0116080",
      "name": "Coats Bend CDP",
      "x": 651.53,
      "y": 384.06,
      "lon": -85.8746,
      "lat": 34.0733,
      "population": null
    },
    {
      "id": "0116240",
      "name": "Coffee Springs town",
      "x": 656.76,
      "y": 438.49,
      "lon": -85.9109,
      "lat": 31.1658,
      "population": null
    },
    {
      "id": "0116264",
      "name": "Coffeeville town",
      "x": 621.29,
      "y": 430.53,
      "lon": -88.086,
      "lat": 31.7666,
      "population": null
    },
    {
      "id": "0116312",
      "name": "Coker town",
      "x": 625.25,
      "y": 402.31,
      "lon": -87.6813,
      "lat": 33.2438,
      "population": null
    },
    {
      "id": "0116600",
      "name": "Collinsville city",
      "x": 651.23,
      "y": 380.42,
      "lon": -85.8686,
      "lat": 34.2672,
      "population": null
    },
    {
      "id": "0116684",
      "name": "Colony town",
      "x": 636.05,
      "y": 388.13,
      "lon": -86.902,
      "lat": 33.9414,
      "population": null
    },
    {
      "id": "0116744",
      "name": "Columbia town",
      "x": 669.18,
      "y": 434.67,
      "lon": -85.1102,
      "lat": 31.2954,
      "population": null
    },
    {
      "id": "0116768",
      "name": "Columbiana city",
      "x": 641.83,
      "y": 401.75,
      "lon": -86.6156,
      "lat": 33.1915,
      "population": null
    },
    {
      "id": "0116936",
      "name": "Concord CDP",
      "x": 634.78,
      "y": 397.32,
      "lon": -87.0404,
      "lat": 33.462,
      "population": null
    },
    {
      "id": "0117176",
      "name": "Coosada town",
      "x": 647.63,
      "y": 414.33,
      "lon": -86.3265,
      "lat": 32.4954,
      "population": null
    },
    {
      "id": "0117368",
      "name": "Cordova town",
      "x": 631.8,
      "y": 391.93,
      "lon": -87.1994,
      "lat": 33.7618,
      "population": null
    },
    {
      "id": "0117704",
      "name": "Cottondale CDP",
      "x": 628.84,
      "y": 402.95,
      "lon": -87.4549,
      "lat": 33.193,
      "population": null
    },
    {
      "id": "0117824",
      "name": "Cottonwood town",
      "x": 666.69,
      "y": 439.51,
      "lon": -85.2996,
      "lat": 31.054,
      "population": null
    },
    {
      "id": "0117968",
      "name": "County Line town",
      "x": 639.15,
      "y": 390.15,
      "lon": -86.7147,
      "lat": 33.8189,
      "population": null
    },
    {
      "id": "0118040",
      "name": "Courtland town",
      "x": 628.27,
      "y": 375.07,
      "lon": -87.3279,
      "lat": 34.6699,
      "population": null
    },
    {
      "id": "0118088",
      "name": "Cowarts town",
      "x": 666.21,
      "y": 436.69,
      "lon": -85.3098,
      "lat": 31.2062,
      "population": null
    },
    {
      "id": "0118304",
      "name": "Creola town",
      "x": 623.91,
      "y": 447.12,
      "lon": -88.0095,
      "lat": 30.8742,
      "population": null
    },
    {
      "id": "0118856",
      "name": "Crossville town",
      "x": 649.2,
      "y": 380.34,
      "lon": -85.9997,
      "lat": 34.2827,
      "population": null
    },
    {
      "id": "0118952",
      "name": "Cuba town",
      "x": 615.72,
      "y": 418.28,
      "lon": -88.3748,
      "lat": 32.4407,
      "population": null
    },
    {
      "id": "0118976",
      "name": "Cullman city",
      "x": 636.56,
      "y": 383.62,
      "lon": -86.8407,
      "lat": 34.1769,
      "population": null
    },
    {
      "id": "0119024",
      "name": "Cullomburg CDP",
      "x": 618.13,
      "y": 431.8,
      "lon": -88.2918,
      "lat": 31.7131,
      "population": null
    },
    {
      "id": "0119216",
      "name": "Cusseta town",
      "x": 662.93,
      "y": 407.16,
      "lon": -85.3058,
      "lat": 32.7876,
      "population": null
    },
    {
      "id": "0119336",
      "name": "Dadeville city",
      "x": 655.55,
      "y": 407.25,
      "lon": -85.7762,
      "lat": 32.8261,
      "population": null
    },
    {
      "id": "0119360",
      "name": "Daleville city",
      "x": 659.67,
      "y": 435.81,
      "lon": -85.7117,
      "lat": 31.2915,
      "population": null
    },
    {
      "id": "0119648",
      "name": "Daphne city",
      "x": 626.4,
      "y": 451.62,
      "lon": -87.8785,
      "lat": 30.6239,
      "population": null
    },
    {
      "id": "0119744",
      "name": "Dauphin Island town",
      "x": 622.29,
      "y": 458.98,
      "lon": -88.1713,
      "lat": 30.2509,
      "population": null
    },
    {
      "id": "0119816",
      "name": "Daviston town",
      "x": 657.28,
      "y": 402.69,
      "lon": -85.6343,
      "lat": 33.0568,
      "population": null
    },
    {
      "id": "0119912",
      "name": "Dayton town",
      "x": 627.34,
      "y": 418.99,
      "lon": -87.6416,
      "lat": 32.351,
      "population": null
    },
    {
      "id": "0120008",
      "name": "Deatsville town",
      "x": 646.48,
      "y": 412.68,
      "lon": -86.3891,
      "lat": 32.589,
      "population": null
    },
    {
      "id": "0120104",
      "name": "Decatur city",
      "x": 633.58,
      "y": 376.41,
      "lon": -86.9899,
      "lat": 34.573,
      "population": null
    },
    {
      "id": "0120152",
      "name": "Deer Park CDP",
      "x": 618.31,
      "y": 441.1,
      "lon": -88.328,
      "lat": 31.2184,
      "population": null
    },
    {
      "id": "0120272",
      "name": "Delta CDP",
      "x": 655.85,
      "y": 395.58,
      "lon": -85.6759,
      "lat": 33.4405,
      "population": null
    },
    {
      "id": "0120296",
      "name": "Demopolis city",
      "x": 624.2,
      "y": 416.46,
      "lon": -87.8267,
      "lat": 32.4997,
      "population": null
    },
    {
      "id": "0120392",
      "name": "Detroit town",
      "x": 616.5,
      "y": 388.25,
      "lon": -88.1678,
      "lat": 34.0274,
      "population": null
    },
    {
      "id": "0120955",
      "name": "Dodge City town",
      "x": 636.12,
      "y": 386.19,
      "lon": -86.8855,
      "lat": 34.0433,
      "population": null
    },
    {
      "id": "0121136",
      "name": "Dora city",
      "x": 633.68,
      "y": 392.39,
      "lon": -87.0813,
      "lat": 33.7281,
      "population": null
    },
    {
      "id": "0121184",
      "name": "Dothan city",
      "x": 664.61,
      "y": 436.35,
      "lon": -85.4068,
      "lat": 31.2337,
      "population": null
    },
    {
      "id": "0121280",
      "name": "Double Springs town",
      "x": 628.22,
      "y": 384.92,
      "lon": -87.3894,
      "lat": 34.1496,
      "population": null
    },
    {
      "id": "0121328",
      "name": "Douglas town",
      "x": 644.48,
      "y": 383,
      "lon": -86.3234,
      "lat": 34.1683,
      "population": null
    },
    {
      "id": "0121448",
      "name": "Dozier town",
      "x": 648.85,
      "y": 432.91,
      "lon": -86.3692,
      "lat": 31.5054,
      "population": null
    },
    {
      "id": "0121890",
      "name": "Dunnavant CDP",
      "x": 642.43,
      "y": 395.95,
      "lon": -86.5402,
      "lat": 33.4952,
      "population": null
    },
    {
      "id": "0121952",
      "name": "Dutton town",
      "x": 649.89,
      "y": 374.13,
      "lon": -85.9119,
      "lat": 34.6062,
      "population": null
    },
    {
      "id": "0122088",
      "name": "Eagle Point CDP",
      "x": 640.5,
      "y": 397.92,
      "lon": -86.6768,
      "lat": 33.4009,
      "population": null
    },
    {
      "id": "0122216",
      "name": "East Brewton city",
      "x": 638.74,
      "y": 441.7,
      "lon": -87.0553,
      "lat": 31.0914,
      "population": null
    },
    {
      "id": "0122504",
      "name": "East Point CDP",
      "x": 637.28,
      "y": 383.28,
      "lon": -86.7923,
      "lat": 34.1912,
      "population": null
    },
    {
      "id": "0122816",
      "name": "Eclectic town",
      "x": 651.8,
      "y": 411.16,
      "lon": -86.0411,
      "lat": 32.6402,
      "population": null
    },
    {
      "id": "0123032",
      "name": "Edgewater CDP",
      "x": 636.01,
      "y": 395.92,
      "lon": -86.9528,
      "lat": 33.5301,
      "population": null
    },
    {
      "id": "0123176",
      "name": "Edwardsville town",
      "x": 658.96,
      "y": 386.84,
      "lon": -85.4141,
      "lat": 33.8837,
      "population": null
    },
    {
      "id": "0123224",
      "name": "Egypt CDP",
      "x": 647.08,
      "y": 384.48,
      "lon": -86.1651,
      "lat": 34.0759,
      "population": null
    },
    {
      "id": "0123296",
      "name": "Elba city",
      "x": 653.64,
      "y": 434.08,
      "lon": -86.0771,
      "lat": 31.4172,
      "population": null
    },
    {
      "id": "0123320",
      "name": "Elberta town",
      "x": 631.33,
      "y": 455.89,
      "lon": -87.5957,
      "lat": 30.3738,
      "population": null
    },
    {
      "id": "0123344",
      "name": "Eldridge town",
      "x": 625.03,
      "y": 389.49,
      "lon": -87.6229,
      "lat": 33.9231,
      "population": null
    },
    {
      "id": "0123488",
      "name": "Elkmont town",
      "x": 633.13,
      "y": 369.64,
      "lon": -86.977,
      "lat": 34.9326,
      "population": null
    },
    {
      "id": "0123656",
      "name": "Elmore town",
      "x": 647.29,
      "y": 413.21,
      "lon": -86.341,
      "lat": 32.5566,
      "population": null
    },
    {
      "id": "0123872",
      "name": "Emelle town",
      "x": 616.2,
      "y": 412.81,
      "lon": -88.3165,
      "lat": 32.7287,
      "population": null
    },
    {
      "id": "0123880",
      "name": "Emerald Mountain CDP",
      "x": 651.35,
      "y": 414.85,
      "lon": -86.0944,
      "lat": 32.4477,
      "population": null
    },
    {
      "id": "0124184",
      "name": "Enterprise city",
      "x": 657.47,
      "y": 435.4,
      "lon": -85.8461,
      "lat": 31.3255,
      "population": null
    },
    {
      "id": "0124256",
      "name": "Epes town",
      "x": 618.97,
      "y": 413.21,
      "lon": -88.142,
      "lat": 32.695,
      "population": null
    },
    {
      "id": "0124280",
      "name": "Equality CDP",
      "x": 650.28,
      "y": 408.95,
      "lon": -86.1232,
      "lat": 32.7657,
      "population": null
    },
    {
      "id": "0124472",
      "name": "Ethelsville town",
      "x": 616.71,
      "y": 399.82,
      "lon": -88.2161,
      "lat": 33.4141,
      "population": null
    },
    {
      "id": "0124568",
      "name": "Eufaula city",
      "x": 667.19,
      "y": 423.28,
      "lon": -85.1527,
      "lat": 31.9099,
      "population": null
    },
    {
      "id": "0124616",
      "name": "Eunola CDP",
      "x": 658.25,
      "y": 440.87,
      "lon": -85.834,
      "lat": 31.0314,
      "population": null
    },
    {
      "id": "0124664",
      "name": "Eutaw city",
      "x": 622.5,
      "y": 410.06,
      "lon": -87.9003,
      "lat": 32.8462,
      "population": null
    },
    {
      "id": "0124688",
      "name": "Eva town",
      "x": 637.44,
      "y": 380.7,
      "lon": -86.7653,
      "lat": 34.3265,
      "population": null
    },
    {
      "id": "0124808",
      "name": "Evergreen city",
      "x": 639.39,
      "y": 435.2,
      "lon": -86.9761,
      "lat": 31.4332,
      "population": null
    },
    {
      "id": "0124880",
      "name": "Excel town",
      "x": 633.58,
      "y": 435.87,
      "lon": -87.3437,
      "lat": 31.4264,
      "population": null
    },
    {
      "id": "0125120",
      "name": "Fairfield city",
      "x": 636.62,
      "y": 396.9,
      "lon": -86.9194,
      "lat": 33.4748,
      "population": null
    },
    {
      "id": "0125216",
      "name": "Fairford CDP",
      "x": 622.42,
      "y": 441.53,
      "lon": -88.0728,
      "lat": 31.178,
      "population": null
    },
    {
      "id": "0125240",
      "name": "Fairhope city",
      "x": 626.55,
      "y": 453.54,
      "lon": -87.8791,
      "lat": 30.5209,
      "population": null
    },
    {
      "id": "0125384",
      "name": "Fairview town",
      "x": 638.92,
      "y": 382,
      "lon": -86.6777,
      "lat": 34.2502,
      "population": null
    },
    {
      "id": "0125648",
      "name": "Falkville town",
      "x": 635.15,
      "y": 379.97,
      "lon": -86.9095,
      "lat": 34.377,
      "population": null
    },
    {
      "id": "0125816",
      "name": "Faunsdale town",
      "x": 627.91,
      "y": 416.93,
      "lon": -87.5938,
      "lat": 32.4576,
      "population": null
    },
    {
      "id": "0125840",
      "name": "Fayette city",
      "x": 622.2,
      "y": 394.07,
      "lon": -87.8312,
      "lat": 33.6942,
      "population": null
    },
    {
      "id": "0125864",
      "name": "Fayetteville CDP",
      "x": 644.55,
      "y": 401.92,
      "lon": -86.4428,
      "lat": 33.1681,
      "population": null
    },
    {
      "id": "0126152",
      "name": "Fitzpatrick CDP",
      "x": 655.27,
      "y": 418.92,
      "lon": -85.8737,
      "lat": 32.2104,
      "population": null
    },
    {
      "id": "0126200",
      "name": "Five Points town",
      "x": 661.74,
      "y": 402.94,
      "lon": -85.3516,
      "lat": 33.0173,
      "population": null
    },
    {
      "id": "0126824",
      "name": "Flomaton town",
      "x": 635.68,
      "y": 443.43,
      "lon": -87.256,
      "lat": 31.0148,
      "population": null
    },
    {
      "id": "0126848",
      "name": "Florala town",
      "x": 650.58,
      "y": 441.84,
      "lon": -86.3182,
      "lat": 31.0224,
      "population": null
    },
    {
      "id": "0126896",
      "name": "Florence city",
      "x": 622.93,
      "y": 372.52,
      "lon": -87.6622,
      "lat": 34.8298,
      "population": null
    },
    {
      "id": "0126992",
      "name": "Foley city",
      "x": 630.13,
      "y": 455.56,
      "lon": -87.6685,
      "lat": 30.3971,
      "population": null
    },
    {
      "id": "0127088",
      "name": "Forestdale CDP",
      "x": 636.74,
      "y": 395.02,
      "lon": -86.9001,
      "lat": 33.5736,
      "population": null
    },
    {
      "id": "0127376",
      "name": "Forkland town",
      "x": 623.33,
      "y": 413.74,
      "lon": -87.8674,
      "lat": 32.6474,
      "population": null
    },
    {
      "id": "0127520",
      "name": "Fort Deposit town",
      "x": 644.84,
      "y": 424.23,
      "lon": -86.5664,
      "lat": 31.9863,
      "population": null
    },
    {
      "id": "0127604",
      "name": "Fort Novosel CDP",
      "x": 659.49,
      "y": 434.86,
      "lon": -85.7161,
      "lat": 31.3426,
      "population": null
    },
    {
      "id": "0127616",
      "name": "Fort Payne city",
      "x": 653.57,
      "y": 376.56,
      "lon": -85.6894,
      "lat": 34.4573,
      "population": null
    },
    {
      "id": "0128024",
      "name": "Franklin town",
      "x": 656.16,
      "y": 414.24,
      "lon": -85.7854,
      "lat": 32.4527,
      "population": null
    },
    {
      "id": "0128120",
      "name": "Fredonia CDP",
      "x": 662.73,
      "y": 403.47,
      "lon": -85.2923,
      "lat": 32.9836,
      "population": null
    },
    {
      "id": "0128312",
      "name": "Frisco City town",
      "x": 632.6,
      "y": 435.71,
      "lon": -87.4042,
      "lat": 31.4395,
      "population": null
    },
    {
      "id": "0128408",
      "name": "Fruitdale CDP",
      "x": 616.79,
      "y": 438.75,
      "lon": -88.4109,
      "lat": 31.3498,
      "population": null
    },
    {
      "id": "0128432",
      "name": "Fruithurst town",
      "x": 659.02,
      "y": 389.76,
      "lon": -85.4312,
      "lat": 33.7295,
      "population": null
    },
    {
      "id": "0128504",
      "name": "Fulton town",
      "x": 626.65,
      "y": 429.62,
      "lon": -87.7442,
      "lat": 31.791,
      "population": null
    },
    {
      "id": "0128552",
      "name": "Fultondale city",
      "x": 638.18,
      "y": 394.05,
      "lon": -86.8014,
      "lat": 33.6174,
      "population": null
    },
    {
      "id": "0128672",
      "name": "Fyffe town",
      "x": 650.31,
      "y": 377.07,
      "lon": -85.9052,
      "lat": 34.449,
      "population": null
    },
    {
      "id": "0128696",
      "name": "Gadsden city",
      "x": 649.49,
      "y": 385.54,
      "lon": -86.0161,
      "lat": 34.0066,
      "population": null
    }
  ],
  "source": "Census TIGER/Line",
  "stroke": "#ef4444",
  "fill": "rgba(239,68,68,0.25)",
  "projectionParams": {
    "scale": 1071.4285714285716,
    "translate": [
      487.5,
      305
    ]
  }
};
export default citiesLayer;
