// AUTO-GENERATED by buildCities.cjs. DO NOT EDIT.
import type { CityLayer } from '../../types';
export const citiesLayer: CityLayer = {
  "key": "cities",
  "label": "Cities (2023)",
  "features": [
    {
      "id": "0646492",
      "name": "Maywood",
      "x": 157.82,
      "y": 354.27,
      "lon": -118.1877,
      "lat": 33.9885,
      "population": null
    },
    {
      "id": "0617750",
      "name": "Cypress",
      "x": 159.31,
      "y": 357.94,
      "lon": -118.0386,
      "lat": 33.8171,
      "population": null
    },
    {
      "id": "0656938",
      "name": "Piedmont",
      "x": 117.34,
      "y": 268.99,
      "lon": -122.2301,
      "lat": 37.8226,
      "population": null
    },
    {
      "id": "0669088",
      "name": "Santa Clarita",
      "x": 155.05,
      "y": 345.33,
      "lon": -118.4992,
      "lat": 34.4156,
      "population": null
    },
    {
      "id": "0613392",
      "name": "Chula Vista",
      "x": 169.8,
      "y": 383.33,
      "lon": -117.0144,
      "lat": 32.6277,
      "population": null
    },
    {
      "id": "0602924",
      "name": "Arvin",
      "x": 153.61,
      "y": 329.86,
      "lon": -118.8306,
      "lat": 35.1944,
      "population": null
    },
    {
      "id": "0671806",
      "name": "Sierra Madre",
      "x": 160.66,
      "y": 351.45,
      "lon": -118.0504,
      "lat": 34.1687,
      "population": null
    },
    {
      "id": "0687056",
      "name": "Yucca Valley",
      "x": 184.86,
      "y": 357.83,
      "lon": -116.4216,
      "lat": 34.1234,
      "population": null
    },
    {
      "id": "0632506",
      "name": "Hawaiian Gardens",
      "x": 158.86,
      "y": 357.58,
      "lon": -118.0728,
      "lat": 33.8303,
      "population": null
    },
    {
      "id": "0665042",
      "name": "San Buenaventura (Ventura)",
      "x": 143.55,
      "y": 345.26,
      "lon": -119.2296,
      "lat": 34.2737,
      "population": null
    },
    {
      "id": "0603526",
      "name": "Bakersfield",
      "x": 151.27,
      "y": 326.17,
      "lon": -119.0392,
      "lat": 35.3551,
      "population": null
    },
    {
      "id": "0617498",
      "name": "Cudahy",
      "x": 157.78,
      "y": 354.75,
      "lon": -118.183,
      "lat": 33.9631,
      "population": null
    },
    {
      "id": "0621712",
      "name": "El Cajon",
      "x": 171.34,
      "y": 380.32,
      "lon": -116.9604,
      "lat": 32.8017,
      "population": null
    },
    {
      "id": "0622594",
      "name": "Emeryville",
      "x": 116.53,
      "y": 268.45,
      "lon": -122.2932,
      "lat": 37.8382,
      "population": null
    },
    {
      "id": "0666000",
      "name": "San Diego",
      "x": 168.99,
      "y": 379.22,
      "lon": -117.1225,
      "lat": 32.8313,
      "population": null
    },
    {
      "id": "0608310",
      "name": "Brisbane",
      "x": 114.24,
      "y": 270.71,
      "lon": -122.4019,
      "lat": 37.6898,
      "population": null
    },
    {
      "id": "0622804",
      "name": "Escondido",
      "x": 171.01,
      "y": 373.83,
      "lon": -117.0723,
      "lat": 33.1345,
      "population": null
    },
    {
      "id": "0659920",
      "name": "Redding",
      "x": 129.64,
      "y": 218.55,
      "lon": -122.3656,
      "lat": 40.5707,
      "population": null
    },
    {
      "id": "0636084",
      "name": "Huron",
      "x": 139.77,
      "y": 306.74,
      "lon": -120.0981,
      "lat": 36.2033,
      "population": null
    },
    {
      "id": "0623126",
      "name": "Exeter",
      "x": 154,
      "y": 308.57,
      "lon": -119.1451,
      "lat": 36.295,
      "population": null
    },
    {
      "id": "0653000",
      "name": "Oakland",
      "x": 117.36,
      "y": 269.61,
      "lon": -122.2169,
      "lat": 37.7913,
      "population": null
    },
    {
      "id": "0604982",
      "name": "Bellflower",
      "x": 158.29,
      "y": 356.33,
      "lon": -118.1271,
      "lat": 33.888,
      "population": null
    },
    {
      "id": "0624638",
      "name": "Folsom",
      "x": 136.84,
      "y": 257.85,
      "lon": -121.1422,
      "lat": 38.6669,
      "population": null
    },
    {
      "id": "0601514",
      "name": "Amador City",
      "x": 140.09,
      "y": 263.57,
      "lon": -120.8232,
      "lat": 38.419,
      "population": null
    },
    {
      "id": "0643000",
      "name": "Long Beach",
      "x": 157.3,
      "y": 357.83,
      "lon": -118.1669,
      "lat": 33.7979,
      "population": null
    },
    {
      "id": "0656112",
      "name": "Patterson",
      "x": 130.91,
      "y": 279.59,
      "lon": -121.1448,
      "lat": 37.4732,
      "population": null
    },
    {
      "id": "0634246",
      "name": "Holtville",
      "x": 195.55,
      "y": 385.32,
      "lon": -115.3779,
      "lat": 32.8129,
      "population": null
    },
    {
      "id": "0645736",
      "name": "Maricopa",
      "x": 144.51,
      "y": 330.38,
      "lon": -119.4054,
      "lat": 35.0517,
      "population": null
    },
    {
      "id": "0651140",
      "name": "Newman",
      "x": 131.89,
      "y": 282.94,
      "lon": -121.0211,
      "lat": 37.3157,
      "population": null
    },
    {
      "id": "0656000",
      "name": "Pasadena",
      "x": 159.3,
      "y": 351.3,
      "lon": -118.139,
      "lat": 34.1598,
      "population": null
    },
    {
      "id": "0633000",
      "name": "Hayward",
      "x": 118.52,
      "y": 273.04,
      "lon": -122.0772,
      "lat": 37.6328,
      "population": null
    },
    {
      "id": "0623910",
      "name": "Ferndale",
      "x": 104.08,
      "y": 210.82,
      "lon": -124.2619,
      "lat": 40.5799,
      "population": null
    },
    {
      "id": "0650132",
      "name": "Muscoy",
      "x": 171.1,
      "y": 354.15,
      "lon": -117.3482,
      "lat": 34.1548,
      "population": null
    },
    {
      "id": "0611656",
      "name": "Casa Conejo",
      "x": 147.39,
      "y": 347.94,
      "lon": -118.9445,
      "lat": 34.1847,
      "population": null
    },
    {
      "id": "0614232",
      "name": "Clyde",
      "x": 121.22,
      "y": 266.11,
      "lon": -122.0278,
      "lat": 38.0252,
      "population": null
    },
    {
      "id": "0618986",
      "name": "Desert Edge",
      "x": 183.78,
      "y": 361.47,
      "lon": -116.4401,
      "lat": 33.9223,
      "population": null
    },
    {
      "id": "0656294",
      "name": "Pearsonville",
      "x": 170.37,
      "y": 321.77,
      "lon": -117.8755,
      "lat": 35.8188,
      "population": null
    },
    {
      "id": "0648676",
      "name": "Monson",
      "x": 152.14,
      "y": 304.26,
      "lon": -119.3358,
      "lat": 36.4927,
      "population": null
    },
    {
      "id": "0614148",
      "name": "Clipper Mills",
      "x": 140.78,
      "y": 241.98,
      "lon": -121.1666,
      "lat": 39.5324,
      "population": null
    },
    {
      "id": "0611376",
      "name": "Carmet",
      "x": 108.43,
      "y": 255.58,
      "lon": -123.072,
      "lat": 38.3743,
      "population": null
    },
    {
      "id": "0640088",
      "name": "Lamont",
      "x": 152.68,
      "y": 328.26,
      "lon": -118.9159,
      "lat": 35.2651,
      "population": null
    },
    {
      "id": "0615030",
      "name": "Comptche",
      "x": 106.04,
      "y": 237.33,
      "lon": -123.5897,
      "lat": 39.2651,
      "population": null
    },
    {
      "id": "0645414",
      "name": "Manila",
      "x": 106.91,
      "y": 206.33,
      "lon": -124.1631,
      "lat": 40.8513,
      "population": null
    },
    {
      "id": "0624526",
      "name": "Floriston",
      "x": 156.04,
      "y": 248.74,
      "lon": -120.0145,
      "lat": 39.393,
      "population": null
    },
    {
      "id": "0681050",
      "name": "Twin Lakes",
      "x": 116.35,
      "y": 285.54,
      "lon": -121.9896,
      "lat": 36.9646,
      "population": null
    },
    {
      "id": "0645820",
      "name": "Marin City",
      "x": 113.6,
      "y": 266.97,
      "lon": -122.5137,
      "lat": 37.8711,
      "population": null
    },
    {
      "id": "0649796",
      "name": "Mount Hermon",
      "x": 115.89,
      "y": 283.71,
      "lon": -122.0533,
      "lat": 37.0511,
      "population": null
    },
    {
      "id": "0655604",
      "name": "Paradise Park",
      "x": 115.81,
      "y": 284.57,
      "lon": -122.0425,
      "lat": 37.0063,
      "population": null
    },
    {
      "id": "0670966",
      "name": "Sequoia Crest",
      "x": 161.04,
      "y": 312.42,
      "lon": -118.6256,
      "lat": 36.1858,
      "population": null
    },
    {
      "id": "0680686",
      "name": "Tulelake",
      "x": 148.62,
      "y": 196.8,
      "lon": -121.4753,
      "lat": 41.9533,
      "population": null
    }
  ],
  "source": "Census TIGER/Line",
  "stroke": "#ef4444",
  "fill": "rgba(239,68,68,0.25)",
  "projectionParams": {
    "scale": 1071.4285714285716,
    "translate": [
      487.5,
      305
    ]
  }
};
export default citiesLayer;
