// AUTO-GENERATED by buildCities.cjs. DO NOT EDIT.
import type { CityLayer } from '../../types';
export const citiesLayer: CityLayer = {
  "key": "cities",
  "label": "Cities (2023)",
  "features": [
    {
      "id": "0100820",
      "name": "Alabaster",
      "x": 638.55,
      "y": 401.55,
      "lon": -86.8243,
      "lat": 33.2192,
      "population": null
    },
    {
      "id": "0160648",
      "name": "Pinson",
      "x": 640.05,
      "y": 392.26,
      "lon": -86.6697,
      "lat": 33.7028,
      "population": null
    },
    {
      "id": "0107456",
      "name": "Blountsville",
      "x": 640.62,
      "y": 385.03,
      "lon": -86.5867,
      "lat": 34.0814,
      "population": null
    },
    {
      "id": "0124664",
      "name": "Eutaw",
      "x": 622.53,
      "y": 410.11,
      "lon": -87.8987,
      "lat": 32.8436,
      "population": null
    },
    {
      "id": "0129392",
      "name": "Geiger",
      "x": 616.03,
      "y": 410.16,
      "lon": -88.3133,
      "lat": 32.8696,
      "population": null
    },
    {
      "id": "0148424",
      "name": "Midway",
      "x": 661.01,
      "y": 420.83,
      "lon": -85.5244,
      "lat": 32.0764,
      "population": null
    },
    {
      "id": "0135392",
      "name": "Hokes Bluff",
      "x": 651.89,
      "y": 385.58,
      "lon": -85.8615,
      "lat": 33.9908,
      "population": null
    },
    {
      "id": "0121184",
      "name": "Dothan",
      "x": 664.61,
      "y": 436.36,
      "lon": -85.4071,
      "lat": 31.2333,
      "population": null
    },
    {
      "id": "0158896",
      "name": "Pell City",
      "x": 646.52,
      "y": 394.29,
      "lon": -86.2667,
      "lat": 33.561,
      "population": null
    },
    {
      "id": "0177784",
      "name": "Union Grove",
      "x": 642.13,
      "y": 378.8,
      "lon": -86.4483,
      "lat": 34.4025,
      "population": null
    },
    {
      "id": "0108248",
      "name": "Bon Air",
      "x": 646.09,
      "y": 399.99,
      "lon": -86.3319,
      "lat": 33.2621,
      "population": null
    },
    {
      "id": "0143744",
      "name": "Loachapoka",
      "x": 658.82,
      "y": 411.08,
      "lon": -85.5948,
      "lat": 32.6049,
      "population": null
    },
    {
      "id": "0119816",
      "name": "Daviston",
      "x": 657.24,
      "y": 402.72,
      "lon": -85.6371,
      "lat": 33.0557,
      "population": null
    },
    {
      "id": "0145784",
      "name": "Madison",
      "x": 636.76,
      "y": 373.48,
      "lon": -86.7638,
      "lat": 34.7115,
      "population": null
    },
    {
      "id": "0162688",
      "name": "Providence",
      "x": 625.25,
      "y": 419.34,
      "lon": -87.7761,
      "lat": 32.3424,
      "population": null
    },
    {
      "id": "0157696",
      "name": "Paint Rock",
      "x": 643.43,
      "y": 373.78,
      "lon": -86.3307,
      "lat": 34.6602,
      "population": null
    },
    {
      "id": "0142160",
      "name": "Leighton",
      "x": 625.17,
      "y": 374.8,
      "lon": -87.5291,
      "lat": 34.6986,
      "population": null
    },
    {
      "id": "0129560",
      "name": "Georgiana",
      "x": 642.64,
      "y": 431,
      "lon": -86.7468,
      "lat": 31.6391,
      "population": null
    },
    {
      "id": "0170704",
      "name": "Sipsey",
      "x": 633.48,
      "y": 390.62,
      "lon": -87.0834,
      "lat": 33.8226,
      "population": null
    },
    {
      "id": "0129296",
      "name": "Gaylesville",
      "x": 655.95,
      "y": 379.89,
      "lon": -85.5585,
      "lat": 34.2681,
      "population": null
    },
    {
      "id": "0148052",
      "name": "Memphis",
      "x": 615.82,
      "y": 405.13,
      "lon": -88.3008,
      "lat": 33.1369,
      "population": null
    },
    {
      "id": "0180064",
      "name": "Waterloo",
      "x": 616.67,
      "y": 371.4,
      "lon": -88.0654,
      "lat": 34.9172,
      "population": null
    },
    {
      "id": "0173728",
      "name": "Sulligent",
      "x": 617.35,
      "y": 390.75,
      "lon": -88.1266,
      "lat": 33.8912,
      "population": null
    },
    {
      "id": "0126896",
      "name": "Florence",
      "x": 622.88,
      "y": 372.51,
      "lon": -87.6651,
      "lat": 34.8306,
      "population": null
    },
    {
      "id": "0151520",
      "name": "Mosses",
      "x": 642.56,
      "y": 420.8,
      "lon": -86.6888,
      "lat": 32.1801,
      "population": null
    },
    {
      "id": "0112160",
      "name": "Carolina",
      "x": 646.93,
      "y": 438.23,
      "lon": -86.5227,
      "lat": 31.2337,
      "population": null
    },
    {
      "id": "0133904",
      "name": "Heath",
      "x": 647.58,
      "y": 435.82,
      "lon": -86.4673,
      "lat": 31.3579,
      "population": null
    },
    {
      "id": "0145496",
      "name": "McKenzie",
      "x": 643.17,
      "y": 432.77,
      "lon": -86.7246,
      "lat": 31.5429,
      "population": null
    },
    {
      "id": "0128936",
      "name": "Gantt",
      "x": 647.21,
      "y": 434.89,
      "lon": -86.4842,
      "lat": 31.4092,
      "population": null
    },
    {
      "id": "0157576",
      "name": "Oxford",
      "x": 652.58,
      "y": 392.99,
      "lon": -85.8679,
      "lat": 33.5958,
      "population": null
    },
    {
      "id": "0150000",
      "name": "Mobile",
      "x": 622.51,
      "y": 450.93,
      "lon": -88.1165,
      "lat": 30.6781,
      "population": null
    },
    {
      "id": "0181504",
      "name": "Westover",
      "x": 642.75,
      "y": 398.31,
      "lon": -86.535,
      "lat": 33.3688,
      "population": null
    },
    {
      "id": "0134096",
      "name": "Henagar",
      "x": 652.44,
      "y": 373.39,
      "lon": -85.7405,
      "lat": 34.631,
      "population": null
    },
    {
      "id": "0179272",
      "name": "Vredenburgh",
      "x": 633.31,
      "y": 428.4,
      "lon": -87.3178,
      "lat": 31.8237,
      "population": null
    },
    {
      "id": "0153376",
      "name": "Natural Bridge",
      "x": 625.08,
      "y": 386.32,
      "lon": -87.6014,
      "lat": 34.0904,
      "population": null
    },
    {
      "id": "0118952",
      "name": "Cuba",
      "x": 615.71,
      "y": 418.27,
      "lon": -88.3755,
      "lat": 32.441,
      "population": null
    },
    {
      "id": "0103940",
      "name": "Banks",
      "x": 656.65,
      "y": 426.28,
      "lon": -85.8364,
      "lat": 31.8132,
      "population": null
    },
    {
      "id": "0157024",
      "name": "Onycha",
      "x": 650.82,
      "y": 438,
      "lon": -86.2785,
      "lat": 31.2246,
      "population": null
    },
    {
      "id": "0137096",
      "name": "Hurtsboro",
      "x": 662.39,
      "y": 417.58,
      "lon": -85.4147,
      "lat": 32.2401,
      "population": null
    },
    {
      "id": "0105140",
      "name": "Belgreen",
      "x": 620.42,
      "y": 379.42,
      "lon": -87.8653,
      "lat": 34.4767,
      "population": null
    },
    {
      "id": "0145316",
      "name": "Macedonia",
      "x": 616.37,
      "y": 400.06,
      "lon": -88.2392,
      "lat": 33.4031,
      "population": null
    },
    {
      "id": "0115256",
      "name": "Clay",
      "x": 641.03,
      "y": 392.24,
      "lon": -86.6067,
      "lat": 33.6983,
      "population": null
    },
    {
      "id": "0181720",
      "name": "Wetumpka",
      "x": 649.45,
      "y": 413.28,
      "lon": -86.2044,
      "lat": 32.5411,
      "population": null
    },
    {
      "id": "0105164",
      "name": "Belk",
      "x": 620.77,
      "y": 395,
      "lon": -87.9287,
      "lat": 33.6515,
      "population": null
    },
    {
      "id": "0182992",
      "name": "Winfield",
      "x": 622.3,
      "y": 389.72,
      "lon": -87.8005,
      "lat": 33.9237,
      "population": null
    },
    {
      "id": "0169978",
      "name": "Shoal Creek",
      "x": 641.51,
      "y": 397.22,
      "lon": -86.6071,
      "lat": 33.4328,
      "population": null
    },
    {
      "id": "0102428",
      "name": "Ariton",
      "x": 659.03,
      "y": 430.09,
      "lon": -85.7128,
      "lat": 31.598,
      "population": null
    },
    {
      "id": "0130640",
      "name": "Goodwater",
      "x": 650.81,
      "y": 403.31,
      "lon": -86.0516,
      "lat": 33.0608,
      "population": null
    },
    {
      "id": "0140096",
      "name": "Kinston",
      "x": 652.54,
      "y": 437.91,
      "lon": -86.1705,
      "lat": 31.22,
      "population": null
    },
    {
      "id": "0153856",
      "name": "New Brockton",
      "x": 656.15,
      "y": 434.54,
      "lon": -85.9228,
      "lat": 31.3784,
      "population": null
    }
  ],
  "source": "Census TIGER/Line",
  "stroke": "#ef4444",
  "fill": "rgba(239,68,68,0.25)",
  "projectionParams": {
    "scale": 1071.4285714285716,
    "translate": [
      487.5,
      305
    ]
  }
};
export default citiesLayer;
