// AUTO-GENERATED by buildCities.cjs. DO NOT EDIT.
import type { CityLayer } from '../../types';
export const citiesLayer: CityLayer = {
  "key": "cities",
  "label": "Cities (2023)",
  "features": [
    {
      "id": "4866128",
      "name": "Schertz",
      "x": 459.57,
      "y": 476.59,
      "lon": -98.251,
      "lat": 29.5642,
      "population": null
    },
    {
      "id": "4806128",
      "name": "Baytown",
      "x": 513.49,
      "y": 473.39,
      "lon": -94.9325,
      "lat": 29.7535,
      "population": null
    },
    {
      "id": "4845000",
      "name": "Lubbock",
      "x": 405.13,
      "y": 399.12,
      "lon": -101.8874,
      "lat": 33.5638,
      "population": null
    },
    {
      "id": "4812412",
      "name": "Canadian",
      "x": 430.4,
      "y": 356.19,
      "lon": -100.3839,
      "lat": 35.9097,
      "population": null
    },
    {
      "id": "4838332",
      "name": "Justin",
      "x": 475.92,
      "y": 410.79,
      "lon": -97.3009,
      "lat": 33.0863,
      "population": null
    },
    {
      "id": "4807396",
      "name": "Bellevue",
      "x": 465.01,
      "y": 400.3,
      "lon": -98.0161,
      "lat": 33.6334,
      "population": null
    },
    {
      "id": "4817612",
      "name": "Creedmoor",
      "x": 468.01,
      "y": 466.85,
      "lon": -97.7431,
      "lat": 30.0943,
      "population": null
    },
    {
      "id": "4803588",
      "name": "Aquilla",
      "x": 476.88,
      "y": 433.96,
      "lon": -97.22,
      "lat": 31.8548,
      "population": null
    },
    {
      "id": "4846668",
      "name": "Marietta",
      "x": 518.84,
      "y": 409.11,
      "lon": -94.5425,
      "lat": 33.1736,
      "population": null
    },
    {
      "id": "4824864",
      "name": "Evant",
      "x": 462.02,
      "y": 440.81,
      "lon": -98.1501,
      "lat": 31.4762,
      "population": null
    },
    {
      "id": "4854132",
      "name": "Orange",
      "x": 532.31,
      "y": 466.25,
      "lon": -93.763,
      "lat": 30.1176,
      "population": null
    },
    {
      "id": "4817000",
      "name": "Corpus Christi",
      "x": 472.39,
      "y": 510.92,
      "lon": -97.4307,
      "lat": 27.7387,
      "population": null
    },
    {
      "id": "4851336",
      "name": "New Summerfield",
      "x": 510.14,
      "y": 431.66,
      "lon": -95.115,
      "lat": 31.9807,
      "population": null
    },
    {
      "id": "4809004",
      "name": "Blum",
      "x": 474.16,
      "y": 428.53,
      "lon": -97.3972,
      "lat": 32.1419,
      "population": null
    },
    {
      "id": "4840696",
      "name": "Lakeport",
      "x": 516.42,
      "y": 423.61,
      "lon": -94.7102,
      "lat": 32.405,
      "population": null
    },
    {
      "id": "4876024",
      "name": "Waelder",
      "x": 475.11,
      "y": 474.45,
      "lon": -97.2972,
      "lat": 29.6943,
      "population": null
    },
    {
      "id": "4811428",
      "name": "Burleson",
      "x": 475.26,
      "y": 421.5,
      "lon": -97.334,
      "lat": 32.5169,
      "population": null
    },
    {
      "id": "4808752",
      "name": "Bloomburg",
      "x": 526.37,
      "y": 409.65,
      "lon": -94.0591,
      "lat": 33.1378,
      "population": null
    },
    {
      "id": "4850820",
      "name": "New Braunfels",
      "x": 461.86,
      "y": 474.1,
      "lon": -98.1133,
      "lat": 29.7,
      "population": null
    },
    {
      "id": "4818020",
      "name": "Crystal City",
      "x": 433.31,
      "y": 492.08,
      "lon": -99.8258,
      "lat": 28.6909,
      "population": null
    },
    {
      "id": "4843996",
      "name": "Loraine",
      "x": 422.21,
      "y": 421.84,
      "lon": -100.7124,
      "lat": 32.4087,
      "population": null
    },
    {
      "id": "4869020",
      "name": "South Houston",
      "x": 508.7,
      "y": 475.16,
      "lon": -95.2285,
      "lat": 29.6611,
      "population": null
    },
    {
      "id": "4863500",
      "name": "Round Rock",
      "x": 469.42,
      "y": 458.79,
      "lon": -97.6644,
      "lat": 30.526,
      "population": null
    },
    {
      "id": "4809448",
      "name": "Booker",
      "x": 428.55,
      "y": 345.78,
      "lon": -100.5402,
      "lat": 36.4561,
      "population": null
    },
    {
      "id": "4852668",
      "name": "Novice",
      "x": 438.96,
      "y": 430.51,
      "lon": -99.6253,
      "lat": 31.9871,
      "population": null
    },
    {
      "id": "4822552",
      "name": "Eden",
      "x": 434.93,
      "y": 444.84,
      "lon": -99.844,
      "lat": 31.2162,
      "population": null
    },
    {
      "id": "4802044",
      "name": "Alma",
      "x": 487.51,
      "y": 426.05,
      "lon": -96.5506,
      "lat": 32.2813,
      "population": null
    },
    {
      "id": "4817917",
      "name": "Cross Timber",
      "x": 475.37,
      "y": 422.13,
      "lon": -97.326,
      "lat": 32.4832,
      "population": null
    },
    {
      "id": "4850496",
      "name": "Nazareth",
      "x": 403,
      "y": 380.52,
      "lon": -102.1021,
      "lat": 34.5418,
      "population": null
    },
    {
      "id": "4873268",
      "name": "Tolar",
      "x": 466.03,
      "y": 423.74,
      "lon": -97.9191,
      "lat": 32.3894,
      "population": null
    },
    {
      "id": "4833608",
      "name": "Higgins",
      "x": 435.92,
      "y": 352.45,
      "lon": -100.0274,
      "lat": 36.121,
      "population": null
    },
    {
      "id": "4821844",
      "name": "Eagle Lake",
      "x": 490.84,
      "y": 476.57,
      "lon": -96.3282,
      "lat": 29.5879,
      "population": null
    },
    {
      "id": "4834148",
      "name": "Hilshire Village",
      "x": 504.47,
      "y": 472.77,
      "lon": -95.4885,
      "lat": 29.7908,
      "population": null
    },
    {
      "id": "4833980",
      "name": "Hillcrest",
      "x": 508.83,
      "y": 480.19,
      "lon": -95.2233,
      "lat": 29.3924,
      "population": null
    },
    {
      "id": "4824000",
      "name": "El Paso",
      "x": 331.55,
      "y": 425.15,
      "lon": -106.4317,
      "lat": 31.849,
      "population": null
    },
    {
      "id": "4836140",
      "name": "Iredell",
      "x": 466.63,
      "y": 431.32,
      "lon": -97.8719,
      "lat": 31.9866,
      "population": null
    },
    {
      "id": "4868504",
      "name": "Smyer",
      "x": 400.9,
      "y": 398.41,
      "lon": -102.1635,
      "lat": 33.5874,
      "population": null
    },
    {
      "id": "4835492",
      "name": "Huntington",
      "x": 518.83,
      "y": 444.7,
      "lon": -94.5772,
      "lat": 31.2803,
      "population": null
    },
    {
      "id": "4840472",
      "name": "Lake City",
      "x": 465.01,
      "y": 504.39,
      "lon": -97.8828,
      "lat": 28.0821,
      "population": null
    },
    {
      "id": "4831964",
      "name": "Hamlin",
      "x": 431.69,
      "y": 413.23,
      "lon": -100.1329,
      "lat": 32.8898,
      "population": null
    },
    {
      "id": "4863524",
      "name": "Round Top",
      "x": 484.92,
      "y": 467.63,
      "lon": -96.6958,
      "lat": 30.064,
      "population": null
    },
    {
      "id": "4830464",
      "name": "Grand Prairie",
      "x": 480.17,
      "y": 418.56,
      "lon": -97.0223,
      "lat": 32.6763,
      "population": null
    },
    {
      "id": "4815976",
      "name": "College Station",
      "x": 491.42,
      "y": 457.9,
      "lon": -96.296,
      "lat": 30.5852,
      "population": null
    },
    {
      "id": "4845744",
      "name": "McKinney",
      "x": 485.81,
      "y": 408.71,
      "lon": -96.6665,
      "lat": 33.2026,
      "population": null
    },
    {
      "id": "4817216",
      "name": "Cotulla",
      "x": 442.83,
      "y": 497.18,
      "lon": -99.2367,
      "lat": 28.4364,
      "population": null
    },
    {
      "id": "4864004",
      "name": "Sabinal",
      "x": 439.59,
      "y": 480.53,
      "lon": -99.4696,
      "lat": 29.3214,
      "population": null
    },
    {
      "id": "4814584",
      "name": "Chester",
      "x": 518.56,
      "y": 451.44,
      "lon": -94.6001,
      "lat": 30.9213,
      "population": null
    },
    {
      "id": "4859192",
      "name": "Poynor",
      "x": 502.6,
      "y": 429.86,
      "lon": -95.5924,
      "lat": 32.0793,
      "population": null
    },
    {
      "id": "4817024",
      "name": "Corral City",
      "x": 477.02,
      "y": 410.58,
      "lon": -97.2304,
      "lat": 33.0985,
      "population": null
    },
    {
      "id": "4857044",
      "name": "Petrolia",
      "x": 461.85,
      "y": 393.07,
      "lon": -98.2312,
      "lat": 34.0132,
      "population": null
    }
  ],
  "source": "Census TIGER/Line",
  "stroke": "#ef4444",
  "fill": "rgba(239,68,68,0.25)",
  "projectionParams": {
    "scale": 1071.4285714285716,
    "translate": [
      487.5,
      305
    ]
  }
};
export default citiesLayer;
