// AUTO-GENERATED by buildCityCoverage.cjs. DO NOT EDIT.
import type { CityCoverageMap, CityCoverageMeta } from '../types';

export const cityCoverageMeta: CityCoverageMeta = {
  "generatedAt": "2025-11-25T02:28:11.870Z",
  "overlayPath": "data/overlays/cities.generated.ts",
  "sourcePath": "data/raw/places/2025_Gaz_place_national.txt",
  "minPopulation": 0,
  "funcstatFilter": "A",
  "overlayFeatureCount": 19262,
  "sourceFeatureCount": 19469,
  "coverageRatio": 0.9884431660588628,
  "topMissing": [
    {
      "id": "0153400",
      "name": "Nauvoo town",
      "stateAbbr": "AL",
      "stateName": "Alabama",
      "population": null
    },
    {
      "id": "0159640",
      "name": "Piedmont city",
      "stateAbbr": "AL",
      "stateName": "Alabama",
      "population": null
    },
    {
      "id": "0179008",
      "name": "Vincent town",
      "stateAbbr": "AL",
      "stateName": "Alabama",
      "population": null
    },
    {
      "id": "0180256",
      "name": "Waverly town",
      "stateAbbr": "AL",
      "stateName": "Alabama",
      "population": null
    },
    {
      "id": "0432020",
      "name": "Hayden town",
      "stateAbbr": "AZ",
      "stateName": "Arizona",
      "population": null
    },
    {
      "id": "0444270",
      "name": "Marana town",
      "stateAbbr": "AZ",
      "stateName": "Arizona",
      "population": null
    },
    {
      "id": "0454050",
      "name": "Peoria city",
      "stateAbbr": "AZ",
      "stateName": "Arizona",
      "population": null
    },
    {
      "id": "0505980",
      "name": "Big Flat town",
      "stateAbbr": "AR",
      "stateName": "Arkansas",
      "population": null
    },
    {
      "id": "0518880",
      "name": "Diamondhead city",
      "stateAbbr": "AR",
      "stateName": "Arkansas",
      "population": null
    },
    {
      "id": "0535040",
      "name": "Jennette town",
      "stateAbbr": "AR",
      "stateName": "Arkansas",
      "population": null
    },
    {
      "id": "0649582",
      "name": "Mountain House city",
      "stateAbbr": "CA",
      "stateName": "California",
      "population": null
    },
    {
      "id": "0812030",
      "name": "Carbonate town",
      "stateAbbr": "CO",
      "stateName": "Colorado",
      "population": null
    },
    {
      "id": "0840550",
      "name": "Keystone town",
      "stateAbbr": "CO",
      "stateName": "Colorado",
      "population": null
    },
    {
      "id": "0875640",
      "name": "Superior town",
      "stateAbbr": "CO",
      "stateName": "Colorado",
      "population": null
    },
    {
      "id": "0877290",
      "name": "Thornton city",
      "stateAbbr": "CO",
      "stateName": "Colorado",
      "population": null
    },
    {
      "id": "1015440",
      "name": "Clayton town",
      "stateAbbr": "DE",
      "stateName": "Delaware",
      "population": null
    },
    {
      "id": "1329528",
      "name": "Fitzgerald city",
      "stateAbbr": "GA",
      "stateName": "Georgia",
      "population": null
    },
    {
      "id": "1332860",
      "name": "Gillsville city",
      "stateAbbr": "GA",
      "stateName": "Georgia",
      "population": null
    },
    {
      "id": "1336528",
      "name": "Haralson town",
      "stateAbbr": "GA",
      "stateName": "Georgia",
      "population": null
    },
    {
      "id": "1345460",
      "name": "Lavonia city",
      "stateAbbr": "GA",
      "stateName": "Georgia",
      "population": null
    }
  ]
};

export const cityCoverage: CityCoverageMap = {
  "IL": {
    "state": "IL",
    "stateName": "Illinois",
    "source": 1294,
    "covered": 1236,
    "coverage": 0.955177743431221,
    "missingExamples": [
      "Amboy city",
      "Aroma Park village",
      "Atkinson town",
      "Bardolph village",
      "Barry city"
    ]
  },
  "AZ": {
    "state": "AZ",
    "stateName": "Arizona",
    "source": 91,
    "covered": 88,
    "coverage": 0.967032967032967,
    "missingExamples": [
      "Hayden town",
      "Marana town",
      "Peoria city"
    ]
  },
  "IN": {
    "state": "IN",
    "stateName": "Indiana",
    "source": 565,
    "covered": 549,
    "coverage": 0.9716814159292035,
    "missingExamples": [
      "Albion town",
      "Aurora city",
      "Beech Grove city",
      "Charlestown city",
      "Cloverdale town"
    ]
  },
  "OH": {
    "state": "OH",
    "stateName": "Ohio",
    "source": 924,
    "covered": 902,
    "coverage": 0.9761904761904762,
    "missingExamples": [
      "Blanchester village",
      "Bloomingburg village",
      "Brinkhaven village",
      "Buckland village",
      "Carrollton village"
    ]
  },
  "NC": {
    "state": "NC",
    "stateName": "North Carolina",
    "source": 549,
    "covered": 539,
    "coverage": 0.9817850637522769,
    "missingExamples": [
      "Candor town",
      "Clayton town",
      "Concord city",
      "Faison town",
      "Falcon town"
    ]
  },
  "DE": {
    "state": "DE",
    "stateName": "Delaware",
    "source": 57,
    "covered": 56,
    "coverage": 0.9824561403508771,
    "missingExamples": [
      "Clayton town"
    ]
  },
  "WI": {
    "state": "WI",
    "stateName": "Wisconsin",
    "source": 608,
    "covered": 598,
    "coverage": 0.9835526315789473,
    "missingExamples": [
      "Ashland city",
      "Burlington city",
      "Columbus city",
      "Greenleaf village",
      "Harrison village"
    ]
  },
  "CO": {
    "state": "CO",
    "stateName": "Colorado",
    "source": 272,
    "covered": 268,
    "coverage": 0.9852941176470589,
    "missingExamples": [
      "Carbonate town",
      "Keystone town",
      "Superior town",
      "Thornton city"
    ]
  },
  "MI": {
    "state": "MI",
    "stateName": "Michigan",
    "source": 533,
    "covered": 526,
    "coverage": 0.9868667917448405,
    "missingExamples": [
      "Baraga village",
      "Cass City village",
      "Cassopolis village",
      "Columbiaville village",
      "Kinde village"
    ]
  },
  "GA": {
    "state": "GA",
    "stateName": "Georgia",
    "source": 536,
    "covered": 529,
    "coverage": 0.9869402985074627,
    "missingExamples": [
      "Fitzgerald city",
      "Gillsville city",
      "Haralson town",
      "Lavonia city",
      "McRae-Helena city"
    ]
  },
  "KS": {
    "state": "KS",
    "stateName": "Kansas",
    "source": 623,
    "covered": 615,
    "coverage": 0.9871589085072231,
    "missingExamples": [
      "De Soto city",
      "Goddard city",
      "Herington city",
      "Jetmore city",
      "St. Marys city"
    ]
  },
  "TN": {
    "state": "TN",
    "stateName": "Tennessee",
    "source": 344,
    "covered": 340,
    "coverage": 0.9883720930232558,
    "missingExamples": [
      "Eagleville city",
      "Farragut town",
      "Smyrna town",
      "Watauga city"
    ]
  },
  "TX": {
    "state": "TX",
    "stateName": "Texas",
    "source": 1224,
    "covered": 1210,
    "coverage": 0.988562091503268,
    "missingExamples": [
      "Clarksville City city",
      "Cleveland city",
      "Dallas city",
      "Fort Worth city",
      "Houston city"
    ]
  },
  "SC": {
    "state": "SC",
    "stateName": "South Carolina",
    "source": 271,
    "covered": 268,
    "coverage": 0.988929889298893,
    "missingExamples": [
      "Pendleton town",
      "Ware Shoals town",
      "West Columbia city"
    ]
  },
  "NY": {
    "state": "NY",
    "stateName": "New York",
    "source": 594,
    "covered": 588,
    "coverage": 0.98989898989899,
    "missingExamples": [
      "Chester village",
      "Dansville village",
      "Geneva city",
      "Hamilton village",
      "Hunter village"
    ]
  },
  "KY": {
    "state": "KY",
    "stateName": "Kentucky",
    "source": 417,
    "covered": 413,
    "coverage": 0.9904076738609112,
    "missingExamples": [
      "Crittenden city",
      "Kevil city",
      "South Park View city",
      "Williamstown city"
    ]
  },
  "NM": {
    "state": "NM",
    "stateName": "New Mexico",
    "source": 105,
    "covered": 104,
    "coverage": 0.9904761904761905,
    "missingExamples": [
      "Mosquero village"
    ]
  },
  "AL": {
    "state": "AL",
    "stateName": "Alabama",
    "source": 463,
    "covered": 459,
    "coverage": 0.9913606911447084,
    "missingExamples": [
      "Nauvoo town",
      "Piedmont city",
      "Vincent town",
      "Waverly town"
    ]
  },
  "OK": {
    "state": "OK",
    "stateName": "Oklahoma",
    "source": 591,
    "covered": 586,
    "coverage": 0.9915397631133672,
    "missingExamples": [
      "Chattanooga town",
      "Clinton city",
      "Mule Barn town",
      "Mulhall town",
      "Seiling city"
    ]
  },
  "MN": {
    "state": "MN",
    "stateName": "Minnesota",
    "source": 856,
    "covered": 849,
    "coverage": 0.991822429906542,
    "missingExamples": [
      "Baldwin city",
      "Becker city",
      "Blaine city",
      "Braham city",
      "Chanhassen city"
    ]
  },
  "NE": {
    "state": "NE",
    "stateName": "Nebraska",
    "source": 528,
    "covered": 524,
    "coverage": 0.9924242424242424,
    "missingExamples": [
      "Atkinson city",
      "Fairmont village",
      "Mead village",
      "Shelton village"
    ]
  },
  "LA": {
    "state": "LA",
    "stateName": "Louisiana",
    "source": 302,
    "covered": 300,
    "coverage": 0.9933774834437086,
    "missingExamples": [
      "St. George city",
      "Tullos town"
    ]
  },
  "MO": {
    "state": "MO",
    "stateName": "Missouri",
    "source": 936,
    "covered": 930,
    "coverage": 0.9935897435897436,
    "missingExamples": [
      "Cape Girardeau city",
      "Corning town",
      "Ionia town",
      "Portageville city",
      "Strafford city"
    ]
  },
  "AR": {
    "state": "AR",
    "stateName": "Arkansas",
    "source": 501,
    "covered": 498,
    "coverage": 0.9940119760479041,
    "missingExamples": [
      "Big Flat town",
      "Diamondhead city",
      "Jennette town"
    ]
  },
  "IA": {
    "state": "IA",
    "stateName": "Iowa",
    "source": 939,
    "covered": 934,
    "coverage": 0.9946751863684771,
    "missingExamples": [
      "Coon Rapids city",
      "Farnhamville city",
      "Greene city",
      "Keota city",
      "Le Grand city"
    ]
  },
  "ID": {
    "state": "ID",
    "stateName": "Idaho",
    "source": 198,
    "covered": 197,
    "coverage": 0.9949494949494949,
    "missingExamples": [
      "Pocatello city"
    ]
  },
  "VA": {
    "state": "VA",
    "stateName": "Virginia",
    "source": 227,
    "covered": 226,
    "coverage": 0.9955947136563876,
    "missingExamples": [
      "Herndon town"
    ]
  },
  "WV": {
    "state": "WV",
    "stateName": "West Virginia",
    "source": 230,
    "covered": 229,
    "coverage": 0.9956521739130435,
    "missingExamples": [
      "Whitesville town"
    ]
  },
  "OR": {
    "state": "OR",
    "stateName": "Oregon",
    "source": 240,
    "covered": 239,
    "coverage": 0.9958333333333333,
    "missingExamples": [
      "Milwaukie city"
    ]
  },
  "UT": {
    "state": "UT",
    "stateName": "Utah",
    "source": 255,
    "covered": 254,
    "coverage": 0.996078431372549,
    "missingExamples": [
      "Bluffdale city"
    ]
  },
  "WA": {
    "state": "WA",
    "stateName": "Washington",
    "source": 281,
    "covered": 280,
    "coverage": 0.99644128113879,
    "missingExamples": [
      "Enumclaw city"
    ]
  },
  "SD": {
    "state": "SD",
    "stateName": "South Dakota",
    "source": 310,
    "covered": 309,
    "coverage": 0.9967741935483871,
    "missingExamples": [
      "Hermosa town"
    ]
  },
  "ND": {
    "state": "ND",
    "stateName": "North Dakota",
    "source": 355,
    "covered": 354,
    "coverage": 0.9971830985915493,
    "missingExamples": [
      "Grandin city"
    ]
  },
  "CA": {
    "state": "CA",
    "stateName": "California",
    "source": 483,
    "covered": 482,
    "coverage": 0.9979296066252588,
    "missingExamples": [
      "Mountain House city"
    ]
  },
  "PA": {
    "state": "PA",
    "stateName": "Pennsylvania",
    "source": 1014,
    "covered": 1012,
    "coverage": 0.9980276134122288,
    "missingExamples": [
      "Mount Lebanon municipality",
      "Penn Hills municipality"
    ]
  },
  "AK": {
    "state": "AK",
    "stateName": "Alaska",
    "source": 149,
    "covered": 149,
    "coverage": 1,
    "missingExamples": []
  },
  "CT": {
    "state": "CT",
    "stateName": "Connecticut",
    "source": 29,
    "covered": 29,
    "coverage": 1,
    "missingExamples": []
  },
  "FL": {
    "state": "FL",
    "stateName": "Florida",
    "source": 411,
    "covered": 411,
    "coverage": 1,
    "missingExamples": []
  },
  "ME": {
    "state": "ME",
    "stateName": "Maine",
    "source": 23,
    "covered": 23,
    "coverage": 1,
    "missingExamples": []
  },
  "MD": {
    "state": "MD",
    "stateName": "Maryland",
    "source": 157,
    "covered": 157,
    "coverage": 1,
    "missingExamples": []
  },
  "MA": {
    "state": "MA",
    "stateName": "Massachusetts",
    "source": 58,
    "covered": 58,
    "coverage": 1,
    "missingExamples": []
  },
  "MS": {
    "state": "MS",
    "stateName": "Mississippi",
    "source": 299,
    "covered": 299,
    "coverage": 1,
    "missingExamples": []
  },
  "MT": {
    "state": "MT",
    "stateName": "Montana",
    "source": 126,
    "covered": 126,
    "coverage": 1,
    "missingExamples": []
  },
  "NV": {
    "state": "NV",
    "stateName": "Nevada",
    "source": 19,
    "covered": 19,
    "coverage": 1,
    "missingExamples": []
  },
  "NH": {
    "state": "NH",
    "stateName": "New Hampshire",
    "source": 13,
    "covered": 13,
    "coverage": 1,
    "missingExamples": []
  },
  "NJ": {
    "state": "NJ",
    "stateName": "New Jersey",
    "source": 323,
    "covered": 323,
    "coverage": 1,
    "missingExamples": []
  },
  "RI": {
    "state": "RI",
    "stateName": "Rhode Island",
    "source": 8,
    "covered": 8,
    "coverage": 1,
    "missingExamples": []
  },
  "VT": {
    "state": "VT",
    "stateName": "Vermont",
    "source": 39,
    "covered": 39,
    "coverage": 1,
    "missingExamples": []
  },
  "WY": {
    "state": "WY",
    "stateName": "Wyoming",
    "source": 99,
    "covered": 99,
    "coverage": 1,
    "missingExamples": []
  }
};

export default cityCoverage;
